[hypervisors]
mprox ansible_host=172.21.16.210 group=hypervisors
msprox ansible_host=172.21.16.130 group=hypervisors

[services]
docker-a ansible_host=172.21.16.211 group=services
pi-services ansible_host=172.21.16.24 group=services
backup ansible_host=172.21.16.212 group=services
